#!/usr/bin/env node

const shell = require('shelljs');
const spawn = require('child_process').spawn
const fs = require('fs');

const getPath = () => {
	if (process.platform === 'darwin') {
	  return '/Applications/Google\ Chrome\ Canary.app/Contents/MacOS/Google\ Chrome\ Canary';
	} else {
	  return shell.exec('which google-chrome').stdout;
	}
};

const chromePath = getPath();
console.log('Spawning chrome path?', chromePath)

var isFirst = true;
var stderr = '';
const program = spawn(chromePath, ['--remote-debugging-port=9222', '--disable-popup-blocking']);

program.stdout.pipe(process.stdout);
program.stderr.pipe(process.stderr);
process.stdin.pipe(program.stdin);

program.on('error', function (err) {
  console.error('Error executing firefox at', chromePath);
  console.error(err.stack);
});

program.on('exit', function(code){
  // Wait few ms for error to be printed.
  setTimeout(function(){
    process.exit(code);
  }, 20)
});

process.on('SIGTERM', function() {
  cp.kill('SIGTERM');
  process.exit(1);
});
